'use client';

import { useEffect, useRef } from 'react';

// Port of the prototype's ANIMATION_7 liquid shader, with proper teardown,
// DPR-aware sizing, a pause when off-screen, and a reduced-motion opt-out.

const VERT = `attribute vec2 a_position;
varying vec2 v_uv;
void main() {
  v_uv = a_position * 0.5 + 0.5;
  gl_Position = vec4(a_position, 0.0, 1.0);
}`;

// Brand-palette rewrite. The original was a purple liquid gradient from an
// unrelated prototype — the single most off-brand thing in the repo, and
// exactly the "generic WebGL" look this site is trying to avoid.
//
// This is closer to paper than to plasma: two slow overlapping wave fields
// pushing terracotta and rose through a cream ground at very low amplitude,
// plus a faint hatch that keeps it reading as printed tone rather than a
// glowing screen effect. Contrast is deliberately tiny — it should register
// as the page surface breathing, not as a graphic competing with the type.
const FRAG = `precision highp float;
uniform float u_time;
uniform vec2 u_resolution;
uniform vec2 u_mouse;
varying vec2 v_uv;

void main() {
  vec2 uv = v_uv;
  float aspect = u_resolution.x / max(u_resolution.y, 1.0);
  vec2 p = vec2(uv.x * aspect, uv.y);
  vec2 mouse = u_mouse / max(u_resolution, vec2(1.0));

  // Domain warp — the coordinates are displaced by a slower field before
  // being sampled. Plain crossed sines gave regular diagonal banding, which
  // read as a different material from the marbled footage running inside the
  // numerals a few hundred pixels away. Warping folds the bands the same way
  // the marble is folded (it is generated by the same idea — see
  // scripts/make-marble.py), so the section ground and the apertures look
  // like one field the page is cut into rather than two unrelated effects.
  vec2 q = vec2(
    sin(p.y * 1.9 + u_time * 0.045),
    cos(p.x * 1.6 - u_time * 0.038)
  );
  vec2 pw = p + 0.35 * q;

  // Speeds roughly halved. At the old rate the drift was perceptible as
  // movement; at this rate you only notice the field has changed if you look
  // away and back, which is what a ground should do.
  float a = sin(pw.x * 2.1 - u_time * 0.055) * 0.5 + 0.5;
  float b = cos(pw.y * 1.7 + u_time * 0.040) * 0.5 + 0.5;
  float c = sin((pw.x + pw.y) * 1.3 + u_time * 0.030) * 0.5 + 0.5;
  float field = (a * 0.4 + b * 0.35 + c * 0.25);

  vec3 paper     = vec3(0.965, 0.969, 0.969); // #f6f7f7
  vec3 rose      = vec3(0.890, 0.698, 0.659); // accent-soft
  vec3 terracotta= vec3(0.651, 0.282, 0.227); // accent

  // Barely there: the strongest tint is ~7% off the paper colour
  vec3 color = mix(paper, rose, smoothstep(0.35, 0.95, field) * 0.16);
  color = mix(color, terracotta, smoothstep(0.72, 1.0, field) * 0.05);

  // A whisper of warmth that follows the pointer, no glow, no radius edge
  float dist = distance(vec2(uv.x * aspect, uv.y), vec2(mouse.x * aspect, mouse.y));
  color = mix(color, rose, smoothstep(0.45, 0.0, dist) * 0.07);

  // Fine horizontal hatch — keeps it feeling like ink on stock
  float hatch = sin(uv.y * u_resolution.y * 0.7) * 0.004;
  color -= hatch;

  gl_FragColor = vec4(color, 1.0);
}`;

export default function ShaderBackground({ className = '' }) {
  const canvasRef = useRef(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const reduced =
      typeof window.matchMedia === 'function' &&
      window.matchMedia('(prefers-reduced-motion: reduce)').matches;

    const gl =
      canvas.getContext('webgl', { antialias: false, alpha: false }) ||
      canvas.getContext('experimental-webgl');
    if (!gl) return;

    const compile = (type, src) => {
      const shader = gl.createShader(type);
      gl.shaderSource(shader, src);
      gl.compileShader(shader);
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) {
        console.warn('Shader compile failed:', gl.getShaderInfoLog(shader));
        gl.deleteShader(shader);
        return null;
      }
      return shader;
    };

    const vs = compile(gl.VERTEX_SHADER, VERT);
    const fs = compile(gl.FRAGMENT_SHADER, FRAG);
    if (!vs || !fs) return;

    const program = gl.createProgram();
    gl.attachShader(program, vs);
    gl.attachShader(program, fs);
    gl.linkProgram(program);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) {
      console.warn('Shader link failed:', gl.getProgramInfoLog(program));
      return;
    }
    gl.useProgram(program);

    const buffer = gl.createBuffer();
    gl.bindBuffer(gl.ARRAY_BUFFER, buffer);
    gl.bufferData(
      gl.ARRAY_BUFFER,
      new Float32Array([-1, -1, 1, -1, -1, 1, 1, 1]),
      gl.STATIC_DRAW
    );
    const posLoc = gl.getAttribLocation(program, 'a_position');
    gl.enableVertexAttribArray(posLoc);
    gl.vertexAttribPointer(posLoc, 2, gl.FLOAT, false, 0, 0);

    const uTime = gl.getUniformLocation(program, 'u_time');
    const uRes = gl.getUniformLocation(program, 'u_resolution');
    const uMouse = gl.getUniformLocation(program, 'u_mouse');

    const mouse = { x: 0.5, y: 0.5 };
    const onPointerMove = (event) => {
      const rect = canvas.getBoundingClientRect();
      if (!rect.width || !rect.height) return;
      mouse.x = (event.clientX - rect.left) / rect.width;
      mouse.y = 1 - (event.clientY - rect.top) / rect.height;
    };
    window.addEventListener('pointermove', onPointerMove, { passive: true });

    const syncSize = () => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      const w = Math.max(1, Math.floor(canvas.clientWidth * dpr));
      const h = Math.max(1, Math.floor(canvas.clientHeight * dpr));
      if (canvas.width !== w || canvas.height !== h) {
        canvas.width = w;
        canvas.height = h;
      }
    };

    let ro;
    if (typeof ResizeObserver !== 'undefined') {
      ro = new ResizeObserver(syncSize);
      ro.observe(canvas);
    } else {
      window.addEventListener('resize', syncSize);
    }
    syncSize();

    let raf = 0;
    let running = true;

    const draw = (timeMs) => {
      syncSize();
      gl.viewport(0, 0, canvas.width, canvas.height);
      gl.uniform1f(uTime, reduced ? 0 : timeMs * 0.001);
      gl.uniform2f(uRes, canvas.width, canvas.height);
      gl.uniform2f(uMouse, mouse.x * canvas.width, mouse.y * canvas.height);
      gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);
    };

    const loop = (t) => {
      if (!running) return;
      draw(t);
      raf = requestAnimationFrame(loop);
    };

    if (reduced) {
      draw(0);
    } else {
      raf = requestAnimationFrame(loop);
    }

    // Pause when the hero scrolls out of view or the tab is hidden.
    const setRunning = (next) => {
      if (reduced) return;
      if (next && !running) {
        running = true;
        raf = requestAnimationFrame(loop);
      } else if (!next && running) {
        running = false;
        cancelAnimationFrame(raf);
      }
    };

    let io;
    if (typeof IntersectionObserver !== 'undefined') {
      io = new IntersectionObserver(
        ([entry]) => setRunning(entry.isIntersecting),
        { threshold: 0 }
      );
      io.observe(canvas);
    }

    const onVisibility = () => setRunning(!document.hidden);
    document.addEventListener('visibilitychange', onVisibility);

    return () => {
      running = false;
      cancelAnimationFrame(raf);
      window.removeEventListener('pointermove', onPointerMove);
      document.removeEventListener('visibilitychange', onVisibility);
      if (ro) ro.disconnect();
      else window.removeEventListener('resize', syncSize);
      if (io) io.disconnect();
      gl.deleteProgram(program);
      gl.deleteShader(vs);
      gl.deleteShader(fs);
      gl.deleteBuffer(buffer);
    };
  }, []);

  return (
    <div className={`pointer-events-none absolute inset-0 ${className}`} aria-hidden="true">
      <canvas ref={canvasRef} className="block h-full w-full" />
      {/* Feather the top and bottom edges into the page so the section has no
          visible canvas boundary — the ground shifts, it doesn't start. */}
      <div className="absolute inset-0 bg-gradient-to-b from-paper via-transparent to-paper" />
    </div>
  );
}
