import { chromium } from 'playwright';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const p=await b.newPage();
await p.route('**/api.web3forms.com/**',async r=>r.fulfill({status:200,body:'{}'}));
await p.goto('http://localhost:3414/contact',{waitUntil:'domcontentloaded'});
await p.waitForSelector('#cf-name',{timeout:15000});
console.log('found');
await p.fill('#cf-name','QA');
console.log('filled ok');
await b.close();
